source 'https://rubygems.org'
gem 'nokogiri'
gem 'open-uri'
gem 'rack', '~> 2.0.1'
gem 'rspec'
gem 'sinatra'
gem 'sinatra-reloader'
gem 'dotenv'
gem 'net-http'
gem 'video_player'
gem "open-uri"
gem "fileutils"